from __future__ import annotations

from enum import Enum, auto, unique


@unique
class Form(Enum):
    Solid = auto()
    Fluid = auto()
    Aux = auto()


@unique
class Item(Enum):
    AdaptiveControlUnit = (auto(), Form.Solid, 76_368)
    AiExpensionServer = (auto(), Form.Solid, 597_652)
    AiLimiter = (auto(), Form.Solid, 920)
    AlcladAluminumSheet = (auto(), Form.Solid, 266)
    AlienDnaCapsule = (auto(), Form.Solid, 0)
    AlienPowerMatrix = (auto(), Form.Solid, 210)
    AlienProtein = (auto(), Form.Solid, 0)
    AluminaSolution = (auto(), Form.Fluid, 0)
    AluminumCasing = (auto(), Form.Solid, 393)
    AluminumIngot = (auto(), Form.Solid, 131)
    AluminumScrap = (auto(), Form.Solid, 27)
    AssemblyDirectorSystem = (auto(), Form.Solid, 500_176)
    AutomatedWiring = (auto(), Form.Solid, 1_440)
    BaconAgaric = (auto(), Form.Solid, 0)
    BallisticWarpDrive = (auto(), Form.Solid, 2_895_334)
    Battery = (auto(), Form.Solid, 465)
    Bauxite = (auto(), Form.Solid, 8)
    BerylNut = (auto(), Form.Solid, 0)
    BiochemicalSculptor = (auto(), Form.Solid, 301_778)
    Biomass = (auto(), Form.Solid, 12)
    BlackPowder = (auto(), Form.Solid, 14)
    BladeRunners = (auto(), Form.Solid, 4_088)
    BluePowerSlug = (auto(), Form.Solid, 0)
    Cable = (auto(), Form.Solid, 24)
    CateriumIngot = (auto(), Form.Solid, 42)
    CateriumOre = (auto(), Form.Solid, 7)
    Chainsaw = (auto(), Form.Solid, 2_760)
    CircuitBoard = (auto(), Form.Solid, 696)
    ClusterNobelisk = (auto(), Form.Solid, 1_376)
    Coal = (auto(), Form.Solid, 3)
    CompactedCoal = (auto(), Form.Solid, 28)
    Computer = (auto(), Form.Solid, 8_352)
    Concrete = (auto(), Form.Solid, 12)
    CoolingSystem = (auto(), Form.Solid, 12_006)
    CopperIngot = (auto(), Form.Solid, 6)
    CopperOre = (auto(), Form.Solid, 3)
    CopperPowder = (auto(), Form.Solid, 72)
    CopperSheet = (auto(), Form.Solid, 24)
    CrudeOil = (auto(), Form.Fluid, 0)
    CrystalOscillator = (auto(), Form.Solid, 3_072)
    DarkMatterCrystal = (auto(), Form.Solid, 1_780)
    DarkMatterResidue = (auto(), Form.Fluid, 0)
    Diamonds = (auto(), Form.Solid, 240)
    DissolvedSilica = (auto(), Form.Fluid, 0)
    ElectromagneticControlRod = (auto(), Form.Solid, 2_560)
    EmptyCanister = (auto(), Form.Solid, 60)
    EmptyFluidTank = (auto(), Form.Solid, 170)
    EncasedIndustrialBeam = (auto(), Form.Solid, 528)
    EncasedPlutoniumCell = (auto(), Form.Solid, 0)
    EncasedUraniumCell = (auto(), Form.Solid, 147)
    ExcitedPhotonicMatter = (auto(), Form.Fluid, 0)
    ExplosiveRebar = (auto(), Form.Solid, 360)
    Fabric = (auto(), Form.Solid, 140)
    FactoryCart = (auto(), Form.Solid, 1_552)
    FicsiteIngot = (auto(), Form.Solid, 1_936)
    FicsiteTrigon = (auto(), Form.Solid, 1_291)
    Ficsonium = (auto(), Form.Solid, 0)
    FicsoniumFuelRod = (auto(), Form.Solid, 0)
    Fuel = (auto(), Form.Fluid, 0)
    FusedModularFrame = (auto(), Form.Solid, 62_840)
    GasFilter = (auto(), Form.Solid, 608)
    GasMask = (auto(), Form.Solid, 14_960)
    GasNobelisk = (auto(), Form.Solid, 544)
    GoldenFactoryCart = (auto(), Form.Solid, 1_852)
    HatcherRemains = (auto(), Form.Solid, 0)
    HazmatSuit = (auto(), Form.Solid, 54_100)
    HeatSink = (auto(), Form.Solid, 2_804)
    HeavyModularFrame = (auto(), Form.Solid, 10_800)
    HeavyOilResidue = (auto(), Form.Fluid, 0)
    HighSpeedConnector = (auto(), Form.Solid, 3_776)
    HogRemains = (auto(), Form.Solid, 0)
    HomingRifleAmmo = (auto(), Form.Solid, 855)
    Hoverpack = (auto(), Form.Solid, 265_632)
    IodineInfusedFilter = (auto(), Form.Solid, 2_274)
    IonizedFuel = (auto(), Form.Fluid, 0)
    IronIngot = (auto(), Form.Solid, 2)
    IronOre = (auto(), Form.Solid, 1)
    IronPlate = (auto(), Form.Solid, 6)
    IronRebar = (auto(), Form.Solid, 8)
    IronRod = (auto(), Form.Solid, 4)
    Jetpack = (auto(), Form.Solid, 16_580)
    Leaves = (auto(), Form.Solid, 0)
    Limestone = (auto(), Form.Solid, 2)
    LiquidBiofuel = (auto(), Form.Fluid, 0)
    MagneticFieldGenerator = (auto(), Form.Solid, 11_000)
    MedicinalInhaler = (auto(), Form.Solid, 125)
    MercerSphere = (auto(), Form.Solid, 0)
    ModularEngine = (auto(), Form.Solid, 9_960)
    ModularFrame = (auto(), Form.Solid, 408)
    Motor = (auto(), Form.Solid, 1_520)
    Mycelia = (auto(), Form.Solid, 0)
    NeuralQuantumProcessor = (auto(), Form.Solid, 248_034)
    NitricAcid = (auto(), Form.Fluid, 0)
    NitrogenGas = (auto(), Form.Fluid, 0)
    Nobelisk = (auto(), Form.Solid, 152)
    NobeliskDetonator = (auto(), Form.Solid, 6_480)
    NonFissileUranium = (auto(), Form.Solid, 0)
    NuclearPasta = (auto(), Form.Solid, 538_976)
    NukeNobelisk = (auto(), Form.Solid, 19_600)
    ObjectScanner = (auto(), Form.Solid, 1_400)
    PackagedAluminaSolution = (auto(), Form.Solid, 160)
    PackagedFuel = (auto(), Form.Solid, 270)
    PackagedHeavyOilResidue = (auto(), Form.Solid, 180)
    PackagedIonizedFuel = (auto(), Form.Solid, 5_246)
    PackagedLiquidBiofuel = (auto(), Form.Solid, 370)
    PackagedNitricAcid = (auto(), Form.Solid, 412)
    PackagedNitrogenGas = (auto(), Form.Solid, 312)
    PackagedOil = (auto(), Form.Solid, 180)
    PackagedRocketFuel = (auto(), Form.Solid, 1_028)
    PackagedSulfuricAcid = (auto(), Form.Solid, 152)
    PackagedTurbofuel = (auto(), Form.Solid, 570)
    PackagedWater = (auto(), Form.Solid, 130)
    Paleberry = (auto(), Form.Solid, 0)
    Parachute = (auto(), Form.Solid, 6_080)
    PetroleumCoke = (auto(), Form.Solid, 20)
    Plastic = (auto(), Form.Solid, 75)
    PlutoniumFuelRod = (auto(), Form.Solid, 153_184)
    PlutoniumPellet = (auto(), Form.Solid, 0)
    PlutoniumWaste = (auto(), Form.Solid, 0)
    PolymerResin = (auto(), Form.Solid, 12)
    PortableMiner = (auto(), Form.Solid, 56)
    PowerShard = (auto(), Form.Solid, 0)
    PressureConversionCube = (auto(), Form.Solid, 255_088)
    PulseNobelisk = (auto(), Form.Solid, 1_533)
    PurplePowerSlug = (auto(), Form.Solid, 0)
    QuartzCrystal = (auto(), Form.Solid, 50)
    Quickwire = (auto(), Form.Solid, 17)
    RadioControlUnit = (auto(), Form.Solid, 32_352)
    RawQuartz = (auto(), Form.Solid, 15)
    ReanimatedSam = (auto(), Form.Solid, 160)
    RebarGun = (auto(), Form.Solid, 1_968)
    ReinforcedIronPlate = (auto(), Form.Solid, 120)
    Rifle = (auto(), Form.Solid, 9_480)
    RifleAmmo = (auto(), Form.Solid, 25)
    RocketFuel = (auto(), Form.Fluid, 0)
    Rotor = (auto(), Form.Solid, 140)
    Rubber = (auto(), Form.Solid, 60)
    Sam = (auto(), Form.Solid, 20)
    SamFluctuator = (auto(), Form.Solid, 1_968)
    Screw = (auto(), Form.Solid, 2)
    ShatterRebar = (auto(), Form.Solid, 332)
    Silica = (auto(), Form.Solid, 20)
    SingularityCell = (auto(), Form.Solid, 114_675)
    SmartPlating = (auto(), Form.Solid, 520)
    SmokelessPowder = (auto(), Form.Solid, 58)
    SolidBiofuel = (auto(), Form.Solid, 48)
    Somersloop = (auto(), Form.Solid, 0)
    SpitterRemains = (auto(), Form.Solid, 0)
    Stator = (auto(), Form.Solid, 240)
    SteelBeam = (auto(), Form.Solid, 64)
    SteelIngot = (auto(), Form.Solid, 8)
    SteelPipe = (auto(), Form.Solid, 24)
    StingerRemains = (auto(), Form.Solid, 0)
    StunRebar = (auto(), Form.Solid, 186)
    Sulfur = (auto(), Form.Solid, 11)
    SulfuricAcid = (auto(), Form.Fluid, 0)
    Supercomputer = (auto(), Form.Solid, 97_352)
    SuperpositionOscillator = (auto(), Form.Solid, 37_292)
    ThermalPropulsionRocket = (auto(), Form.Solid, 728_508)
    TimeCrystal = (auto(), Form.Solid, 960)
    TurboMotor = (auto(), Form.Solid, 240_496)
    TurboRifleAmmo = (auto(), Form.Solid, 120)
    Turbofuel = (auto(), Form.Fluid, 0)
    Uranium = (auto(), Form.Solid, 35)
    UraniumFuelRod = (auto(), Form.Solid, 43_468)
    UraniumWaste = (auto(), Form.Solid, 0)
    VersatileFramework = (auto(), Form.Solid, 1_176)
    Water = (auto(), Form.Fluid, 0)
    Wire = (auto(), Form.Solid, 6)
    Wood = (auto(), Form.Solid, 0)
    XenoBasher = (auto(), Form.Solid, 17_800)
    XenoZapper = (auto(), Form.Solid, 1_880)
    YellowPowerSlug = (auto(), Form.Solid, 0)
    Zipline = (auto(), Form.Solid, 5_284)

    AwesomeTicketPoints = (auto(), Form.Aux, 0)
    MwPower = (auto(), Form.Aux, 0)

    def _generate_next_value_(name, start, count, last_values):  # noqa: N805
        return name

    def __init__(self, value, form: Form, points: int):
        self.form = form
        self.points = points

    def __mul__(self, rhs: float):
        from .rates import Rates

        return Rates({self: rhs})

    def __str__(self):
        return self.name

    def __repr__(self):
        return str(self)


def sinkable(item: Item) -> bool:
    return item.form == Form.Solid and item.points > 0
