from .recipe import all, converter, default, raw

recipe_banks = {
    "All": all(),
    "All - Conversions": [r for r in all() if r.name not in [x.name for x in converter()]],
    "All - RawSupply": [r for r in all() if r.name not in [x.name for x in raw()]],
    "All - Conversions - RawSupply": [r for r in all() if r.name not in [x.name for x in converter() + raw()]],
    "Default": default(),
    "Default + Conversions": default() + converter(),
    "Default + RawSupply": default() + raw(),
    "Default + Conversions + RawSupply": default() + converter() + raw(),
    "Multiplayer": [r for r in all() if r.name not in [x.name for x in converter() + raw()]],
    "Clandestine": default()
    + [
        r
        for r in all()
        if r.name
        in [
            "IronWire",
            "EncasedIndustrialPipe",
            "StitchedIronPlate",
            "WetConcrete",
            "AutomatedMiner",
            "SteelScrew",
            "CastScrew",
            "SolidSteelIngot",
            "SteamedCopperSheet",
            "SteelRotor",
            "IronAlloyIngot",
            "MoldedBeam",
            "IronPipe",
            "DilutedPackagedFuel",
            "HeavyEncasedFrame",
            "RecycledPlastic",
            "HeavyOilResidue",
            "RecycledRubber",
            "PureCopperIngot",
            "FusedQuickwire",
            "CateriumCircuitBoard",
            "CrystalComputer",
            "InsulatedCrystalOscillator",
            "PureCateriumIngot",
            "PlasticAiLimiter",
            "CokeSteelIngot",
            "PolymerResin",
            "MoldedSteelPipe",
            "TemperedCateriumIngot",
            "FineConcrete",
            "CopperAlloyIngot",
            "SteelRod",
            "SteeledFrame",
            "BoltedIronPlate",
            "FlexibleFramework",
            "PlasticSmartPlating",
            "CheapSilica",
            "AutomatedSpeedWiring",
            "SloppyAlumina",
            "PureAluminumIngot",
            "ElectrodeAluminumScrap",
            "SiliconCircuitBoard",
            "AlcladCasing",
            "RadioControlSystem",
            "DilutedFuel",
            "BasicIronIngot",
            "CateriumComputer",
            "ClassicBattery",
            "PureIronIngot",
            "TurboBlendFuel",
            "TemperedCopperIngot",
            "FusedWire",
            "PureQuartzCrystal",
            "InstantScrap",
            "ElectrodeCircuitBoard",
            "SiliconHighSpeedConnector",
            "AluminumBeam",
            "CateriumWire",
            "BoltedFrame",
            "LeachedCateriumIngot",
            "HeavyFlexibleFrame",
            "AdheredIronPlate",
            "QuickwireCable",
            "AluminumRod",
            "InsulatedCable",
            "CompactedSteelIngot",
            "CoatedCable",
            "FineBlackPowder",
            "CompactedCoal",
            "PolyesterFabric",
        ]
    ],
}
