version: "3.9"
services:
    duckbot:
        healthcheck:
            test: ["CMD", "python", "-m", "duckbot.health"]
            start_period: 10s
            interval: 60s
            retries: 5
        deploy:
            mode: replicated
            replicas: 1
            restart_policy:
                condition: any
                window: 10s
            update_config:
                failure_action: rollback
                monitor: 90s
                order: stop-first
            rollback_config:
                monitor: 90s
                order: stop-first

    postgres:
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "duckbot"]
            start_period: 10s
            interval: 60s
            timeout: 5s
            retries: 5
        deploy:
            mode: replicated
            replicas: 1
            restart_policy:
                condition: any
                window: 10s
            update_config:
                failure_action: rollback
                monitor: 90s
                order: stop-first
            rollback_config:
                monitor: 90s
                order: stop-first
