version: "3.9"
services:
    duckbot:
        healthcheck:
            test: ["CMD", "python", "-m", "duckbot.health"]
            start_period: 10s
            interval: 60s
            retries: 3
        restart: always

    postgres:
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "duckbot"]
            start_period: 10s
            interval: 60s
            timeout: 5s
            retries: 3
        restart: always

    autoheal:
        image: willfarrell/autoheal
        restart: always
        environment:
            AUTOHEAL_START_PERIOD: "5"
            AUTOHEAL_CONTAINER_LABEL: all
