# The docker-compose file for production environment, with healthchecks and automatic container restarts.
version: "3.9"
services:
    duckbot:
        healthcheck:
            test: ["CMD", "python", "-m", "duckbot.health"]
            start_period: 10s
            interval: 60s
            retries: 3
        restart: always
        deploy:
            mode: replicated
            replicas: 1
            restart_policy:
                condition: any
                window: 10s
            update_config:
                failure_action: rollback
                monitor: 300s
                order: start-first
            rollback_config:
                order: stop-first

    postgres:
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "duckbot"]
            start_period: 10s
            interval: 60s
            timeout: 5s
            retries: 3
        restart: always
        deploy:
            mode: replicated
            replicas: 1
            restart_policy:
                condition: any
                window: 10s
            update_config:
                failure_action: rollback
                monitor: 300s
                order: start-first
            rollback_config:
                order: stop-first

    # autoheal:
    #     image: willfarrell/autoheal
    #     restart: always
    #     environment:
    #         AUTOHEAL_START_PERIOD: "10"
    #         AUTOHEAL_INTERVAL: "30"
    #         AUTOHEAL_CONTAINER_LABEL: all
    #     volumes:
    #     - /var/run/docker.sock:/var/run/docker.sock
