AWSTemplateFormatVersion: 2010-09-09

Parameters:
  DuckBotImageTag:
    Type: String
    Default: latest

Resources:
  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: duckbot

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: duckbot
      ContainerDefinitions:
      - Name: duckbot
        Image: !Sub "twentylemon/duckbot:${DuckBotImageTag}"
        Essential: true
        Secrets: # FIXME must also specify executionRoleArn
        - Name: DISCORD_TOKEN
          ValueFrom: /duckbot/token/discord
        - Name: OPENWEATHER_TOKEN
          ValueFrom: /duckbot/token/openweather
        HealthCheck:
          Command: [CMD, python, -m, duckbot.health]
          Interval: 60
          Timeout: 10
          Retries: 3
          StartPeriod: 10
      - Name: postgres
        Image: "postgres:13.2"
        Essential: false
        Environment:
        - Name: POSTGRES_USER
          Value: duckbot
        - Name: POSTGRES_PASSWORD
          Value: pond
        MountPoints:
        - SourceVolume: duckbot_dbdata
          ContainerPath: /var/lib/postgrsql/data
          ReadOnly: false
        HealthCheck:
          Command: [CMD, pg_isready, -U, duckbot]
          Interval: 60
          Timeout: 5
          Retries: 3
          StartPeriod: 10
      Volumes:
      - Name: duckbot_dbdata
        DockerVolumeConfiguration:
          Scope: shared
          Autoprovision: true
          Driver: local
      Memory: 960
      RequiresCompatibilities: [EC2]

  Host:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-09bee01cc997a78a6
      InstanceType: t2.micro
      UserData: !Base64
        Fn::Sub: |
          #!/bin/bash -xe
          echo ECS_CLUSTER=${Cluster} >> /etc/ecs/ecs.config

  Service:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !GetAtt Cluster.Arn
      ServiceName: duckbot
      DesiredCount: 1
      TaskDefinition: !Ref TaskDefinition
      LaunchType: EC2
