AWSTemplateFormatVersion: 2010-09-09

Parameters:
  DuckBotImageTag:
    Type: String
    Default: latest
  DiscordToken:
    Type: String
    NoEcho: true
  OpenweatherToken: # FIXME move to parameter store
    Type: String
    NoEcho: true

Resources:
  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: duckbot

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: duckbot
      ContainerDefinitions:
      - Name: duckbot
        Image: !Sub "twentylemon/duckbot:${DuckBotImageTag}"
        Essential: true
        Environment:
        - Name: DISCORD_TOKEN
          Value: !Sub ${DiscordToken}
        - Name: OPENWEATHER_TOKEN
          Value: !Sub ${OpenweatherToken}
        HealthCheck:
          Command: [CMD, python, -m, duckbot.health]
          Interval: 60
          Timeout: 10
          Reties: 3
          StartPeriod: 10
      - Name: postgres
        Image: "postgres:13.2"
        Essential: false
        Environment:
        - Name: POSTGRES_USER
          Value: duckbot
        - Name: POSTGRES_PASSWORD
          Value: pond
        MountPoints:
        - SourceVolume: duckbot_dbdata
          ContainerPath: /var/lib/postgrsql/data
          ReadOnly: false
        HealthCheck:
          Command: [CMD, pg_isready, -U, duckbot]
          Interval: 60
          Timeout: 5
          Reties: 3
          StartPeriod: 10
      Volumes:
      - Name: duckbot_dbdata
        DockerVolumeConfiguration:
          Scope: shared
          Autoprovision: true
          Driver: local
      Memory: 960
      RequiresCompatibilities: [EC2]
