from .bitcoin import Bitcoin
from .duck import Duck
from .insights import Insights
from .kubernetes import Kubernetes
from .recipe import Recipe
from .tito import Tito
from .typos import Typos
from .weather import Weather
from .who_can_it_be_now import WhoCanItBeNow
from .formula_one import FormulaOne
from .fortune import Fortune
from .message_modified import MessageModified
