from .bitcoin import Bitcoin
from .duck import Duck
from .kubernetes import Kubernetes
from .recipe import Recipe
from .thanking_robot import ThankingRobot
from .tito import Tito
from .typos import Typos
from .weather import Weather
from .formula_one import FormulaOne
from .fortune import Fortune
from .message_modified import MessageModified
