name: Build and Push DuckBot Docker Image
description: builds and pushes the duckbot docker image to docker hub

inputs:
  docker-pass:
    description: the docker hub password
    required: true

outputs:
  latest:
    description: the docker image tag for the latest version
    value: ${{ steps.image.outputs.latest }}
  commit:
    description: the docker image tag for the specific commit version
    value: ${{ steps.image.outputs.commit }}

runs:
  using: composite
  steps:
  - uses: actions/checkout@v3

  - name: Create Docker Image Tags
    id: image
    shell: bash
    run: |
      echo "latest=duckdynasty/duckbot:latest" >> $GITHUB_OUTPUT
      echo "commit=duckdynasty/duckbot:$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

  - name: Set up Docker Buildx
    uses: docker/setup-buildx-action@v2

  - name: Set up Docker Build Cache
    uses: actions/cache@v3
    with:
      path: /tmp/.buildx-cache
      key: ${{ runner.os }}-buildx-${{ github.sha }}
      restore-keys: ${{ runner.os }}-buildx-

  - name: Login to Docker
    uses: docker/login-action@v2
    with:
      username: duckdynasty
      password: ${{ inputs.docker-pass }}

  - name: Build and Push Docker Image
    shell: bash
    run: |
      docker buildx build . \
        --tag ${{ steps.image.outputs.latest }} \
        --tag ${{ steps.image.outputs.commit }} \
        --platform=linux/amd64 \
        --cache-from='type=local,src=/tmp/.buildx-cache' \
        --cache-to='type=local,dest=/tmp/.buildx-cache' \
        --push
