# https://discord.com/developers/docs/resources/channel#embed-limits
MAX_EMBED_LENGTH = 6000
MAX_TITLE_LENGTH = 256
MAX_DESCRIPTION_LENGTH = 4096
MAX_FIELDS = 25
MAX_FIELD_NAME_LENGTH = 256
MAX_FIELD_VALUE_LENGTH = 1024
MAX_FOOTER_LENGTH = 2048
MAX_AUTHOR_NAME_LENGTH = 256
