taunts = {
    "1": "Yes.",
    "2": "No.",
    "3": "Food please.",
    "4": "Wood please.",
    "5": "Gold please.",
    "6": "Stone please.",
    "7": "Ahh!",
    "8": "All hail, king of the losers!",
    "9": "Ooh!",
    "10": "I'll beat you back to Age of Empires.",
    "11": "(Herb laugh)",
    "12": "Ah! Being rushed!",
    "13": "Sure, blame it on your ISP.",
    "14": "Start the game already!",
    "15": "Don't point that thing at me!",
    "16": "Enemy sighted!",
    "17": "It is good to be the king.",
    "18": "Monk! I need a monk!",
    "19": "Long time, no siege.",
    "20": "My granny could scrap better than that.",
    "21": "Nice town, I'll take it.",
    "22": "Quit touching me!",
    "23": "Raiding party!",
    "24": "Dadgum.",
    "25": "Eh, smite me.",
    "26": "The wonder, the wonder, the... no!",
    "27": "You played two hours to die like this?",
    "28": "Yeah, well, you should see the other guy.",
    "29": "Roggan.",
    "30": "Wololo.",
    "31": "Attack an enemy now.",
    "32": "Cease creating extra villagers.",
    "33": "Create extra villagers.",
    "34": "Build a navy.",
    "35": "Stop building a navy.",
    "36": "Wait for my signal to attack.",
    "37": "Build a wonder.",
    "38": "Give me your extra resources.",
    "39": "(Ally sound)",
    "40": "(Neutral sound)",
    "41": "(Enemy sound)",
    "42": "What age are you in?",
    "43": "What is your strategy?",
    "44": "How many resources do you have?",
    "45": "Retreat now!",
    "46": "Flare the location of your army.",
    "47": "Attack in direction of the flared location.",
    "48": "I'm being attacked, please help!",
    "49": "Build a forward base at the flared location.",
    "50": "Build a fortification at the flared location.",
    "51": "Keep your army close to mine and fight with me.",
    "52": "Build a market at the flared location.",
    "53": "Rebuild your base at the flared location.",
    "54": "Build a wall between the two flared locations.",
    "55": "Build a wall around your town.",
    "56": "Train units which counter the enemy's army.",
    "57": "Stop training counter units.",
    "58": "Prepare to send me all your resources so I can vanquish our foes!",
    "59": "Stop sending me extra resources.",
    "60": "Prepare to train a large army, I will send you as many resources as I can spare.",
    "61": "Attack player 1! (Blue)",
    "62": "Attack player 2! (Red)",
    "63": "Attack player 3! (Green)",
    "64": "Attack player 4! (Yellow)",
    "65": "Attack player 5! (Cyan)",
    "66": "Attack player 6! (Purple)",
    "67": "Attack player 7! (Gray)",
    "68": "Attack player 8! (Orange)",
    "69": "Delete the object on the flared location.",
    "70": "Delete your excess villagers.",
    "71": "Delete excess warships.",
    "72": "Focus on training infantry units.",
    "73": "Focus on training cavalry units.",
    "74": "Focus on training ranged units.",
    "75": "Focus on training warships.",
    "76": "Attack the enemy with Militia.",
    "77": "Attack the enemy with Archers.",
    "78": "Attack the enemy with Skirmishers.",
    "79": "Attack the enemy with a mix of Archers and Skirmishers.",
    "80": "Attack the enemy with Scout Cavalry.",
    "81": "Attack the enemy with Men-at-Arms.",
    "82": "Attack the enemy with Eagle Scouts.",
    "83": "Attack the enemy with Towers.",
    "84": "Attack the enemy with Crossbowmen.",
    "85": "Attack the enemy with Cavalry Archers.",
    "86": "Attack the enemy with Unique Units.",
    "87": "Attack the enemy with Knights.",
    "88": "Attack the enemy with Battle Elephants.",
    "89": "Attack the enemy with Scorpions.",
    "90": "Attack the enemy with Monks.",
    "91": "Attack the enemy with Monks and Mangonels.",
    "92": "Attack the enemy with Eagle Warriors.",
    "93": "Attack the enemy with Halberdiers and Rams.",
    "94": "Attack the enemy with Elite Eagle Warriors.",
    "95": "Attack the enemy with Arbalests.",
    "96": "Attack the enemy with Champions.",
    "97": "Attack the enemy with Galleys.",
    "98": "Attack the enemy with Fire Galleys.",
    "99": "Attack the enemy with Demolition Rafts.",
    "100": "Attack the enemy with War Galleys.",
    "101": "Attack the enemy with Fire Ships.",
    "102": "Attack the enemy with Unique Warships.",
    "103": "Use an Onager to cut down trees at the flared location.",
    "104": "Don't resign!",
    "105": "You can resign again.",
}
