name: Stale Issues/Pull Requests

permissions:
  issues: write
  pull-requests: write

on:
  schedule:
  - cron: '7 13 * * MON'
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v10
      with:
        only-labels: needs reply  # only consider items which are manually labelled 'needs reply'
        labels-to-remove-when-unstale: needs reply
        days-before-stale: 30  # things go stale after a month
        days-before-close: 30  # close stale things after another month
        stale-issue-label: stale
        stale-pr-label: stale
        stale-pr-message: Yo dawg, get some traction on this or it'll be yeeted. Brother.
        close-pr-message: YEET
        stale-issue-message: Yo dawg, get some traction on this or it'll be yeeted. Brother.
        close-issue-message: YEET
