on:
  pull_request:
    types:
    - opened

jobs:
  roll:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/rickroll
      with:
        chance: 100
