name: Memes

on:
  pull_request_target:
    types:
    - opened
  issues:
    types:
    - opened

jobs:
  roll:
    runs-on: ubuntu-latest
    steps:
    - uses: duck-dynasty/rick-roll-action@latest
      with:
        chance: 2
