name: Set Up Python Virtual Environment
description: creates a python virtual environment for duckbot

inputs:
  extras:
    description: duckbot package extras to install
    required: false
    default: none  # pip warns about extras not existing, but otherwise is ok with it
  path:
    description: where to place the virtual environment relative to repository root
    required: false
    default: venv

outputs:
  path:
    description: path to the created virtual environment relative to repository root
    value: ${{ steps.path.outputs.path }}

runs:
  using: composite
  steps:
  - uses: actions/checkout@v3
  - name: Set up Python 3.8
    uses: actions/setup-python@v4
    with:
      python-version: 3.8
      cache: pip
      cache-dependency-path: setup.py

  - name: Create path Output
    id: path
    shell: bash
    run: echo "path=${{ inputs.path }}" >> $GITHUB_OUTPUT

  - name: Install Packages
    shell: bash
    run: |
      python -m venv --clear ${{ steps.path.outputs.path }}
      . ${{ steps.path.outputs.path }}/bin/activate
      pip install --upgrade pip setuptools wheel
      SETUPTOOLS_ENABLE_FEATURES="legacy-editable" pip install --editable .[${{ inputs.extras }}]
