name: Set Up Python Virtual Environment
description: creates a python virtual environment for duckbot

inputs:
  extras:
    description: duckbot package extras to install
    required: false
    default: none  # pip warns about extras not existing, but otherwise is ok with it
  path:
    description: where to place the virtual environment relative to repository root
    required: false
    default: venv

outputs:
  path:
    description: path to the created virtual environment relative to repository root
    value: ${{ steps.path.outputs.path }}

runs:
  using: composite
  steps:
  - uses: actions/checkout@v6
  - name: Set up Python
    uses: actions/setup-python@v6
    with:
      python-version: '3.10'

  - name: Create path Output
    id: path
    shell: bash
    run: echo "path=${{ inputs.path }}" >> $GITHUB_OUTPUT

  - name: Set up Virtual Environment Cache
    id: venv
    uses: actions/cache@v4
    with:
      path: ${{ steps.path.outputs.path }}
      key: ${{ env.pythonLocation }}-${{ inputs.extras }}-${{ hashFiles('pyproject.toml') }}

  - name: Install Packages
    if: steps.venv.outputs.cache-hit != 'true'
    shell: bash
    run: |
      python -m venv --clear ${{ steps.path.outputs.path }}
      . ${{ steps.path.outputs.path }}/bin/activate
      pip install --editable .[${{ inputs.extras }}]
      setup_nltk
